repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: no-commit-to-branch # default: main, master
      - id: trailing-whitespace
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.3.2
    hooks:
      - id: markdownlint-cli2
        name: Lint markdown files
