site_name: "We care about Renningen - we live here and we love here."
site_description: "We share information we think important for the residents."
site_url: "https://nicolefinnie.github.io/we-care-renningen"
repo_url: "https://github.com/nicolefinnie/we-care-renningen"
edit_uri: "edit/main/.docs"
repo_name: "nicolefinnie/we-care-renningen"

docs_dir: .docs
site_dir: .site

nav:
  - Information:
      - Aktuelle Information : index.md
      - Flyer: flyer.md
  - About Us: about.md

theme:
  logo: res/krautgaerten.jpg
  name: material
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: slate
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      toggle:
        icon: material/eye
        name: Switch to dark mode

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - search
